# Generated by Django 3.2.9 on 2021-11-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('cedula_nit', models.CharField(blank=True, db_column='Cedula_NIT', max_length=45, null=True)),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_productos', models.AutoField(db_column='ID_productos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('precio_unitario', models.PositiveIntegerField(blank=True, db_column='Precio_unitario', null=True)),
                ('cant_stock', models.PositiveIntegerField(blank=True, db_column='Cant_stock', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField(blank=True, db_column='Fecha_orden', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('total', models.PositiveIntegerField(blank=True, db_column='Total', null=True)),
                ('tipo_pago', models.CharField(blank=True, db_column='Tipo_pago', max_length=45, null=True)),
                ('Contacto', models.ForeignKey(db_column='contacto_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_productos.contacto')),
            ],
            options={
                'db_table': 'facturacion',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturacion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('subtotal', models.FloatField(blank=True, db_column='Subtotal', null=True)),
                ('descuento', models.FloatField(blank=True, db_column='Descuento', null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, db_column='Cantidad', null=True)),
                ('facturacion', models.ForeignKey(db_column='Facturacion_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_productos.facturacion')),
                ('inventario_id_productos', models.ForeignKey(db_column='Inventario_ID_productos', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_productos.inventario')),
            ],
            options={
                'db_table': 'detalle_facturacion',
            },
        ),
    ]
