# Generated by Django 3.2.9 on 2021-11-07 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tipo_contacto',
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='id_tipo_contacto',
            field=models.ForeignKey(db_column='id_TipoContacto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_productos.tipocontacto'),
        ),
    ]
